<h1>NON GRADED CHALLENGE 5</h1>

1. Buatlah Tensor dibawah ini dengan Python:

$$\begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}$$
  
  
  
 
 

2. Lakukan perkalian terhadap matrix berikut:

 $$A =
\begin{bmatrix}
23 & 50 & 19 \\
7 & 12 & 109 \\
57 & 67 & 98
\end{bmatrix}
\begin{bmatrix}
17 \\
22 \\
19
\end{bmatrix}
 $$

3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:
$$
\begin{bmatrix}
23 & 50 & 19 \\
7 & 12 & 109 \\
57 & 67 & 98
\end{bmatrix}
$$
 


Import Library yang akan digunakan

In [38]:
import numpy as np

Jawaban nomor 1

In [39]:
X = [23, 50, 7, 12,
     57, 67, 99, 43,
     75, 21, 57, 12,
     87, 26, 18, 84]
MatrixX = np.array(X).reshape(4,2,2)
print(MatrixX.shape)
MatrixX

(4, 2, 2)


array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

Jawaban nomor 2

In [40]:
A = [23, 50, 19,
     7, 12, 109,
     57, 67, 98] 
B = [17,22,19]
MatA = np.array(A).reshape(3,3)
MatB = np.array(B)
print(MatA.shape)

MatA@MatB

(3, 3)


array([1852, 2454, 4305])

Jawaban nomor 3

In [41]:
Transpose = MatA.T # Transpose matrix
Transpose

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [42]:
np.linalg.det(MatA) #Determinan Matrix

131344.0000000002

In [43]:
np.linalg.inv(MatA) #Invers Matrix

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])