<h1>NON GRADED CHALLENGE 6</h1>

Apakah 
$$\begin{bmatrix}1\\ 3 \end{bmatrix}$$

adalah eigenvector dari 
$$\begin{bmatrix}1 & -1\\ 6 &-4 \end{bmatrix}$$
Jika iya, berapakah eigenvalue-nya?

In [2]:
import numpy as np #import library numpy dan berikan alias np

In [6]:
A = [1,3] #masukan matrix pertama ke dalam variable A
matA = np.array(A).reshape(1,2)
B = [1,-1,6,-4]#masukan matrix kedua ke dalam variable B
matB = np.array(B).reshape(2,2)
print (matA,"\n")
print (matB)

[[1 3]] 

[[ 1 -1]
 [ 6 -4]]


In [12]:
values, vector = np.linalg.eig(matB) # mencari eigen vector dari matrix B
print(vector)
print(values)

[[0.4472136  0.31622777]
 [0.89442719 0.9486833 ]]
[-1. -2.]


dari hasil diatas, bisa dilihat bahwa vektor A bukan merupakan eigenvector dari matrix B